AWSTemplateFormatVersion: "2010-09-09"
Description:

Parameters:
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro

Resources:
  EC2mikko:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: !Ref InstanceTypeParameter
      ImageId: !Ref LatestAmiId
      Tags:
        - Key: Owner
          Value: Mikko
        - Key: Name
          Value: mikko-ec2-cf
      KeyName: mikon-demo-ec2
      SecurityGroupIds:
          - Ref: InstanceSecurityGroup