AWSTemplateFormatVersion: 2010-09-09
Description: Mikon CloudFormation Demo

# Parameters: Latest Ami Id, Instance Type Parameter, myVPC
# Resouces: EC2mikko, InstanceSecurityGroup, S3 ampari, SQSservice, ALBalancer, ALB security group,
# Outputs: BackupLoadBalancerDNSName


Parameters:
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
  myVPC:
    Type: String
    Default: vpc-bc8f6cc1

Resources:

  EC2mikko:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: !Ref InstanceTypeParameter
      ImageId: !Ref LatestAmiId
      Tags:
        - Key: Owner
          Value: Mikko
        - Key: Name
          Value: HuugiBuugi
      KeyName: mikon-demo-ec2
      SecurityGroupIds:
        - Type: String
          Ref: InstanceSecurityGroup

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: mikko-CF-sg
      GroupDescription: Allow http to client host
      VpcId:
        Ref: myVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  Ampari:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: mikon-cloudformation-malliampari
      Tags:
        - Key: Owner
          Value: Mikko

  SQSservice:
    Type: 'AWS::SQS::Queue'
    Properties:
      QueueName: mikko-sqs
      Tags:
        - Key: Owner
          Value: Mikko

  ALBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: ipv4
      Name: HuugiBuugiBalancer
      Scheme: internet-facing
      Subnets:
        - subnet-f9a8b3c7
        - subnet-b693f4fb
        - subnet-94bf68f2
      Tags:
        - Key: Owner
          Value: Mikko
      Type: application

  ALBsg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SecurityGroup_for_ALB
      GroupName: mikko-alb-sg
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: ssh
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Owner
          Value: Mikko
      VpcId: !Ref myVPC

Outputs:
  BackupLoadBalancerDNSName:
    Description: The DNSName of the backup load balancer
    Value: !GetAtt ALBalancer.DNSName


#aws cloudformation deploy --template-file luo_s3_ampari.yaml --stack-name mikon-s3-stack