AWSTemplateFormatVersion: 2010-09-09
Description: Mikon CloudFormation Demo

Resources:
  Ampari:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: mikon-cloudformation-malliampari
      Tags:
        - Key: Owner
          Value: Mikko
  SQSservice:
    Type: 'AWS::SQS::Queue'
    Properties:
      QueueName: mikko-sqs
      Tags:
        - Key: Owner
          Value: Mikko
